language: go
sudo: required

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

go_import_path: github.com/atlassian/escalator
go:
  - "1.13.x"

before_install:
  # install goreturns for linting
  - go get -u github.com/sqs/goreturns

script:
  - make lint
  - make test
  - make test-race
  - make test-vet
  - make build
